const fs = require("fs");

function generateMarkdown(answers) {
// set the answers to a variable  
let info =  `
# ${answers.title}
# ${answers.badge}

Table of contents:
(#Description)
(#Install Instructions)
(#Usage Instructions)
(#License)
(#Contributors)
(#Tests)
(#Contact Information)

# ${answers.description}
# ${answers.install}
# ${answers.usage}
# ${answers.license}
# ${answers.contributors}
# ${answers.test}

#
# ${answers.githubPic}
# ${answers.email}

`;




// write the info generated by the answers from the prompts
  fs.writeFile("ReadMe.md", info, (err)=> {
  if (err) {
    throw err;
  }
  console.log("file saved to README");
})
}
module.exports = generateMarkdown;
