const fs = require("fs");

function generateMarkdown(answers) {
// set the answers to a variable  
let info =  `
# ${answers.title}
# ${answers.badge}

# Table of contents:
* [Description](#description)
* [Install Instructions](#install-instructions)
* [Usage Instructions](#usage-instructions)
* [License](#license)
* [Contributors](#contributors)
* [Tests](#tests)
* [Contact Information](#contact-information)

# Description:


 ${answers.description}
# Install Instructions:


 ${answers.install}
# Usage Instructions:


 ${answers.usage}
# License:


 ${answers.license}
# Contributors:


 ${answers.contributors}
# Tests:


 ${answers.test}

# Contact Information:


 [!myImage](${answers.githubPic})


 ## Email: <${answers.email}>

`;




// write the info generated by the answers from the prompts to a file called ReadMe.md
  fs.writeFile("ReadMe.md", info, (err)=> {
  if (err) {
    throw err;
  }
  console.log("file saved to README");
})
}
module.exports = generateMarkdown;
