const fs = require("fs");

function generateMarkdown(answers) {
// set the answers to a variable  
let info =  `
# ${answers.title}
# ${answers.badge}

##Table of contents:
(#Description)
(#Install Instructions)
(#Usage Instructions)
(#License)
(#Contributors)
(#Tests)
(#Contact Information)

#Description 
${answers.description}
#Install Instructions
# ${answers.install}
#Usage Instructions
# ${answers.usage}
#License
# ${answers.license}
#Contributors
# ${answers.contributors}
#Tests
# ${answers.test}

#Contact Information
# ${answers.githubPic}
# ${answers.email}

`;




// write the info generated by the answers from the prompts to a file called ReadMe.md
  fs.writeFile("ReadMe.md", info, (err)=> {
  if (err) {
    throw err;
  }
  console.log("file saved to README");
})
}
module.exports = generateMarkdown;
